### ISSUE TITLE
[FEA] Support host-side decompression

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#211]
User reports indicate it being common to have high compression ratios on input files, such that after decompressing, raw data-sizes is in the 10+ GB range.

dask-cudf follows core Dask in not supporting decompressing files prior to loading into a DataFrame. Perhaps Dask doesn't need decompression prior to load because host memory is usually sufficient to handle large decompressed files?

In any case, GPU memory is much smaller than host memory. Given that high compression ratios are common, it would be a significant ease-of-use win to support decompressing and thus being able to split inputs prior to loading into cuDF DataFrames.

**Comment by mrocklin** [comment]
What kinds of files?  What kinds of compression?

**Comment by mrocklin** [comment]
Or, to be more clear, most common file compression formats (gzip, bz2) don't support random access, so in common case this isn't a choice of ours, it's just the way things are.

**Comment by randerzander** [comment]
CSV and gzip, specifically.

I left these off the initial description because I partially expect that to be the case for Parquet and ORC files too. Will confirm here if I hear of/find examples of that happening.

**Comment by mrocklin** [comment]
> CSV and gzip, specifically.

I'm not sure what we can do here in that case.  GZip doesn't provide random access, so we can't make a bunch of tasks that say "go read this section of the file".  

For Parquet and Orc I don't think that this is likely to be an issue.  Chunks there tend to be more reasonably sized.

**Comment by mrocklin** [comment]
Suggestions would be welcome if you have thoughts on how to accomplish what you want.  I've never found a great solution though, other than not storing analysis data as giant gzip files.

**Comment by randerzander** [comment]
Sorry I wasn't clearer. I'm suggesting something like a param that if True, lets Dask perform host-side decompression first, then workers can be assigned byte ranges to read from the decompressed file.

**Comment by mrocklin** [comment]
So we would call something like `$ gunzip usersfile.csv' first, and then run?  If so, I'm going to raise a few complications:

-  Where would we save this file?  Do we have write permissions?
-  Would we then delete the file afterwards?  How can we make sure that this happens?
-  What happens if the user points us to many csv files
-  What happens if those files are on cloud storage / HDFS?

I ask these questions mostly to bring up the point that this can get complicated quickly, and will likely lead to a bunch of odd bugs (you're leaving giant CSV files all over my hard drive!) that I'd prefer not to have to deal with.

Instead, I think I'd prefer to not handle this internally, and instead ask users to do it explicitly.

What might be more helpful is if we were to warn if users try to open up a giant gzipped CSV file.  We do this a bit now, but maybe we could include the filesize or something similar to be particularly loud?

**Comment by mrocklin** [comment]
@randerzander is there anything more to do here?  Sorry not to have a solution for you on this problem.
