### ISSUE TITLE
Testing / CI 

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cudf#49]
I'm not sure I understand the current CI system.  It looks like we're building conda packages.  

Instead, I'm inclined to conda install `dask` and `cudf` and then run `py.test`, leaving package builds to release time.  

Any objection to my tearing things down here?

cc @mike-wendt @kkraus14

**Comment by mrocklin** [comment]
I just remembered that we're going to need GPU hardware to run tests of any sort here.  Presumably we'll need the same sort of treatment used in the `rapidsai/cudf` repository.

**Comment by mrocklin** [comment]
@mike-wendt is this the right place to raise this sort of issue or should I do something else to make sure that it's on your radar (or whoever is likely to handle this within NVIDIA?)

**Comment by mike-wendt** [comment]
This is on our radar but will slip until next week. Given that we are at HQ our priority is the hardware and lab due to the need for physical access.

There are ways that you can help us get this up and going faster:
* Provide a build script similar to this one: https://github.com/rapidsai/gpuci-build-environment/blob/master/build-scripts/pygdf-master.sh
* Review the common container that we use for cuDF/cuML CI builds: https://github.com/rapidsai/gpuci-build-environment/blob/master/Dockerfile
  * Report mismatches in versions dependencies or configuration (some of these can be addressed in the build script)
  * Typically we are testing with gcc 5/7 on Ubuntu 16.04 at the moment with CUDA 9.2/10.0

If helpful I can post what is in the Jenkins script that Keith made months ago, but I think it is probably very out of date and better to start fresh

**Comment by mike-wendt** [comment]
Also worth pointing out these are live versions used by cuDF https://github.com/rapidsai/cudf/tree/branch-0.6/ci

**Comment by mike-wendt** [comment]
> @mike-wendt is this the right place to raise this sort of issue or should I do something else to make sure that it's on your radar (or whoever is likely to handle this within NVIDIA?)

For this I will have a fix out on Monday that will help with issues like this, not just for me but for the entire team. Please assign people to issues you need them to handle and that will work well with the upcoming fix.

**Comment by mrocklin** [comment]
No rush on any of this really.  Thanks for putting it on your radar.  I'll assign people in the future.

**Comment by mike-wendt** [comment]
@mrocklin so I can get this implemented, do you have someone on your team that can help build the files mentioned above? These will control the build and test process

**Comment by mrocklin** [comment]
cc @quasiben

**Comment by mike-wendt** [comment]
> @mrocklin so I can get this implemented, do you have someone on your team that can help build the files mentioned above? These will control the build and test process

@quasiben specifically I need `dask-cudf` versions of these files https://github.com/rapidsai/cudf/tree/branch-0.6/ci

**Comment by quasiben** [comment]
@mike-wendt sounds.  I'll start working on this shortly

**Comment by mike-wendt** [comment]
@quasiben let me know when you have a PR, I'll add in what I can if you need help

**Comment by mike-wendt** [comment]
during the PR we should also drop all Travis CI references but they may be useful to keep around for a bit until we have the conversion complete as they are a good reference
