### ISSUE TITLE
dtype handing in CSV is incorrect

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cudf#85]
## Data

```
a,b,c
1.2,2017-01-09 11:13:28,N
1.2,2017-01-09 11:13:28,N
1.2,2017-01-09 11:13:28,N
```

## Code
```python
import dask_cudf

gdf = dask_cudf.read_csv('dtype-test.csv', chunksize='30 B')
print(gdf.head().to_pandas())
```

## Error
> libgdf_cffi.wrapper.GDFError: GDF_UNSUPPORTED_DTYPE

I think this is also an error on the cudf side as cudf inspects the dtypes as `[dtype('float64') dtype('<M8[ms]') dtype('int32')]` which is incorrect.  

One possible solution right now is to drop the dtype setting in csv.py

cc @mrocklin

**Comment by mrocklin** [comment]
This is because we get a dtype in the first chunk that ends up not being
correct?

If so then solution for this in dask dataframe was to raise very
informative errors that direct users to supply a correct dtype= keyword.
This is one of the things that we might skip on until we can eventually
merge the two.

**Comment by quasiben** [comment]
I believe that is correct.  What additionally makes things somewhat challenging at the moment is `parse_date` is still a feature request https://github.com/rapidsai/cudf/issues/721 and cudf blows up when defining the dtype directly.  I'll file an issue now with cudf
